// Crypt.idl

interface CaesarAlgorithm {
	typedef sequence<char> charsequence;
	charsequence encrypt(in string info,in unsigned long k,in unsigned long shift);
	string decrypt(in charsequence info,in unsigned long k,in unsigned long shift);
	boolean shutdown();
};
		  
