package CaesarAlgorithm;
// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright(c) 2002 - 2010 Progress Software Corporation (PSC).  All
// rights reserved.  Use, reproduction, transfer, publication or
// disclosure is prohibited except as specifically provided for in
// your License Agreement with PSC.
//
// **********************************************************************

// Version: 4.3.4

//
// IDL:CaesarAlgorithm:1.0
//
/***/

public interface CaesarAlgorithm extends CaesarAlgorithmOperations,
                                         org.omg.CORBA.Object,
                                         org.omg.CORBA.portable.IDLEntity
{
}
