package CaesarAlgorithm;
// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright(c) 2002 - 2010 Progress Software Corporation (PSC).  All
// rights reserved.  Use, reproduction, transfer, publication or
// disclosure is prohibited except as specifically provided for in
// your License Agreement with PSC.
//
// **********************************************************************

// Version: 4.3.4

//
// IDL:CaesarAlgorithm:1.0
//
final public class CaesarAlgorithmHolder implements org.omg.CORBA.portable.Streamable
{
    public CaesarAlgorithm value;

    public
    CaesarAlgorithmHolder()
    {
    }

    public
    CaesarAlgorithmHolder(CaesarAlgorithm initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = CaesarAlgorithmHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        CaesarAlgorithmHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return CaesarAlgorithmHelper.type();
    }
}
